//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisTrainingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoroughStaffMem
    {
        public int Key { get; set; }
        public string Type { get; set; }
        public int StaffID { get; set; }
        public string BoroughID { get; set; }
    
        public virtual Borough Borough { get; set; }
    }
}
