//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisTrainingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Centres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cost_Centres()
        {
            this.Staff1 = new HashSet<Staff>();
        }
    
        public int Code { get; set; }
        public string CCName { get; set; }
        public Nullable<int> Site { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<int> Directorate { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Specialty { get; set; }
        public bool Enbld { get; set; }
        public Nullable<int> Director { get; set; }
        public Nullable<int> Manager_1 { get; set; }
        public Nullable<int> Manager_2 { get; set; }
        public Nullable<int> Budget_1 { get; set; }
        public Nullable<int> Budget_2 { get; set; }
        public Nullable<int> Budget_3 { get; set; }
        public Nullable<int> Board { get; set; }
        public Nullable<int> SLRserv { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Modifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff1 { get; set; }
    }
}
