//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisTrainingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESRStaff
    {
        public decimal iEmployee { get; set; }
        public decimal cEmployee { get; set; }
        public Nullable<int> Title { get; set; }
        public string Forename { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string Staff_Code { get; set; }
        public bool Already_Setup { get; set; }
        public string UUID { get; set; }
        public Nullable<bool> NHS_Pension { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Modifier { get; set; }
    }
}
