//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisTrainingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Leads = new HashSet<Team>();
            this.Attendances = new HashSet<Attendance>();
            this.Reqs = new HashSet<Req>();
            this.Sessions = new HashSet<Sess>();
            this.StaffManaged = new HashSet<Staff>();
            this.TeamApprovs = new HashSet<TeamApprov>();
            this.TeamMems = new HashSet<TeamMem>();
        }
    
        public int ID { get; set; }
        public Nullable<short> TitleID { get; set; }
        public string Fname { get; set; }
        public string Sname { get; set; }
        public string PName { get; set; }
        public Nullable<byte> GenderID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> FinanceCode { get; set; }
        public Nullable<int> JobStatusCode { get; set; }
        public Nullable<int> LineManID { get; set; }
        public Nullable<int> CohortID { get; set; }
        public string UUID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsLM { get; set; }
        public Nullable<bool> IsTrainer { get; set; }
        public Nullable<bool> HasLeftTrust { get; set; }
        public Nullable<bool> NoTraining { get; set; }
        public Nullable<bool> IsBank { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<int> ESRID { get; set; }
        public string MName { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> Modifier { get; set; }
        public string ADAccount { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        public virtual Cost_Centres CostCentre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Leads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual RA RA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Req> Reqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sess> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> StaffManaged { get; set; }
        public virtual Staff LineManager { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamApprov> TeamApprovs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMem> TeamMems { get; set; }
        public virtual TNA TNA { get; set; }
        public virtual Subjective Subjective { get; set; }
    }
}
