//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisTrainingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public short ID { get; set; }
        public string StatusDescription { get; set; }
        public bool IsRequirement { get; set; }
        public bool IsAttendance { get; set; }
        public bool IsRA_PDS { get; set; }
        public bool IsTNA_OUT { get; set; }
        public bool IsRA_PLUS { get; set; }
        public bool IsRA_ESR { get; set; }
    }
}
