//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisTrainingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public short ID { get; set; }
        public string TheTitle { get; set; }
        public string Genders { get; set; }
        public Nullable<byte> DGen { get; set; }
    }
}
